@extends('frontend.layout.master2')

@section('title', 'Terms of use')

@section('content')
    <div class="container">
        <p>Welcome to ........., a website owned and operated by ....... Limited, a Hong Kong limited liability company (".........", "we" or "us"). The following page explains the terms and conditions by which you may use our web site, mobile device software applications, Application Program Interface and any other mobile or web services or applications owned, controlled, or offered by ......... and its affiliates available through .......... (collectively, the "Site") whether as a guest or a registered user. By accessing or using the Site, or by acknowledging your consent through any interface required to access the Site, you represent that you have read, understood and agree to be bound by the following terms of use (the "Terms of Use Agreement" or "Agreement") and our privacy policy available at <a href="/privacy">.............</a> and by this reference incorporated herein ("Privacy Policy"). Please read the Agreement carefully before proceeding and using the Site. In addition, when you use any current or future ........ service or visit or purchase from any business affiliated with us, whether or not included in the <a href="/">................com</a> website, you also will be subject to the terms and conditions applicable to such service or business. If you do not want to agree to this Agreement or the Privacy Policy, you must not access or use the Site.</p>
        <h5>ACCEPTANCE OF AGREEMENT</h5>
        <p>Your use of the Site constitutes your acceptance of the terms and conditions outlined in this Terms of Use Agreement and in each of our policies posted on our website. This Terms of Use Agreement, together with each of our policies posted on our website, are collectively referred to herein as the "Site Policies." The Terms of Use Agreement constitutes the entire and only agreement between us and you concerning the subject matter of the Terms of Use Agreement and supersedes all prior or contemporaneous agreements, representations, warranties and understandings concerning the subject matter of the Terms of Use Agreement. We reserve the right to make changes to our Site, Content (as defined below), Services (as defined below), this Terms of Use Agreement and the Site Policies from time to time at our sole discretion. We may make such revisions without prior notice to you, so please check back often for updates. Unless otherwise provided in such revision, any revision to our Site, this Terms of Use Agreement or the Site Policies, or part thereof, will take effect when they are posted.</p>
        <h5>PRIVACY</h5>
        <p>Please review our Privacy Policy <a href="/privacy">................com/privacy</a>, which also governs your visit to our Site and all information ............... collects or that you provide on this Site, to understand our practices concerning privacy matters. By using the Site, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy. Furthermore, you agree that all information you provide to register with this Site or otherwise, including but not limited to the use of any of the interactive features on the Site, is governed by the Privacy Policy.</p>
        <h5>ELECTRONIC COMMUNICATIONS</h5>
        <p>When you visit ................com or send e-mails to us, you are communicating with us electronically. You acknowledge that you can access information that is provided electronically, and you consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this website. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
        <h5>OUR SERVICES</h5>
        <p>We provide you with the opportunity to follow companies, create information feeds, view and access competitive intelligence reports, provide information about companies on the Site and use other services that may be provided from time to time on the Site (the "Services"). Notwithstanding anything contained herein to the contrary, we reserve the right to withdraw or amend this Site, and any Service or material we provide on the Site, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Site is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Site, or the entire Site, to users, including registered users.</p>
        <h5>REGISTRATION</h5>
        <p>When you register on our Site for the use of our Services, you agree to provide true, accurate, current and complete information about yourself as required by our registration application, and to maintain and promptly update the information provided by you in order to keep it true, accurate, current and complete. You further agree that you are not in violation of any trade secret or confidentiality agreement and otherwise have the right to provide all information you submit to the Site. You further agree that you are creating the account for yourself, and not for a third party. In addition, you agree that you will comply with all policies of the Site, including this Terms of Use Agreement. You agree to provide accurate data and information when using the Site, and that you will answer all questions, polls and complete all tasks to the best of your ability and using information that you believe to be truthful. You agree not to use the Services or access the Site with malicious intent. You also represent that you are not a person barred from receiving our Services under the laws of Hong Kong or any other applicable jurisdiction. By using the Site, you represent that you are over the age of 13. If you do not comply with the foregoing conditions or any of the terms and conditions set forth in this Agreement, or we reasonably suspect that information provided by you is in violation of the foregoing conditions, you must not access or use the Site and we have the right to suspend or terminate your account and refuse any and all current or future use of our Services (or any portion thereof).</p>
        <p>To register for an account online, you must have a valid email address. In addition to your email address, you must provide us with your first and last name, employer and job function and a secure password. We may also request you provide us with your phone number, as well as any social media profiles you may have. Your use of our Services constitutes express permission for us to use the information you provide and any personal information from your social media profiles. If you download the ............... application or "app" onto your smartphone you agree to permit us to generate a unique identifier for your app installation and to pre-register you on our system. By downloading the app, you agree to be bound by this Terms of Use Agreement. You agree to provide registration information if we ask for such information at a later date. If you do not provide us with registration information, your access to the app and to the ............... Site and Services may be revoked. By providing your email address, you consent to receiving emails from ................</p>
        <p>We assume no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings. You are responsible for obtaining access to our Services, and that access may involve third-party fees (such as Internet service provider or airtime charges). If you use your mobile device to access our Site or use our Services, you understand that you are responsible for any fees that your mobile service provider charges for data or SMS services. In addition, you must provide and are responsible for all equipment necessary to access our Services.</p>
        <h5>PAID SERVICES</h5>
        <p>If you sign up for any paid services, you agree to pay the subscription fees associated with the service as well as any applicable taxes. We do not store any credit card information. By providing your credit card information to our third-party credit card processing partner, you are agreeing to abide by the processor’s terms and conditions and authorizing the processor to charge your card during the subscription term. Your credit card will be charged for pre-paid subscriptions or each month for month-to-month subscriptions until we received notice from you to terminate your paid subscription. You are responsible for providing accurate and current credit card information. If payment does not go through for any reason, your account may be suspended, and we will have no obligation to provide services until the billing issue has been resolved and we receive payment from the processor. ............... reserves the right to change its pricing and services at any time.</p>
        <p>If you no longer wish to receive paid services, it is your responsibility to cancel your subscription. Subscription fees are non-refundable, except when required by law. If you pre-pay for a subscription in order to take advantage of a discounted rate, you are agreeing to pay for the entire subscription period, and the charges will apply even if you terminate your account before the end of the subscription period.</p>
        <h5>ACCOUNT SECURITY</h5>
        <p>If you choose or are provided with, a user name, password or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to this Site or portions of it using your user name, password or other security information. You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information.</p>
        <p>We have the right to disable any user name, password or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of this Agreement. We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders at our sole discretion.</p>
        <p>If you feel that your account has been compromised, you agree to contact us immediately at <a href="mailto:help@................com">help@................com</a>.</p>
        <h5>NON-TRANSFERABILITY</h5>
        <p>Your right to use our website is not transferable or assignable. Any password or right given to you to obtain information or access the Site is not transferable or assignable and any attempt to transfer your rights to another party may result in suspension or termination of your account.</p>
        <h5>OWNERSHIP OF DATA</h5>
        <p>When you submit information to us, follow a company, answer poll questions, or complete any other tasks through the Site, you irrevocably grant, transfer and convey to us all right, title and interest in and to the materials and content provided, including all intellectual property rights therein. You agree we have the unlimited and unconditional right to distribute, exploit and use in perpetuity, anywhere and everywhere in the universe, in any media and by any means now known or hereafter devised, any materials, photographs, statements, compositions, submissions, tasks, responses to polls and questions, trends, information regarding the companies you follow and what you follow, biographies, and/or other content, whether written, spoken, or otherwise expressed by you, including your name and employment information (collectively, the "Published Information") provided by you on the Site. We shall have the right to use, store, market, promote, edit, incorporate, distribute, reproduce, display, perform, transmit, advertise, re-use, re-distribute, and re-transmit the Published Information at our own option using any method at our discretion without any payment or other obligation to you. Company may therefore, without payment or other obligation to you, reproduce, edit, distribute, publicly display and digitally perform and/or distribute the Published Information in whole or in part, alone or together with other material, on all media (including but not limited to the Internet, other web sites, television, videos/DVDs, cell phones, CDs and radio), and in any format by any means now known or hereafter devised. We shall also have the right to use the Published Information in order to promote our products and services and to use your name, picture, photograph, and your profile without any payment to you. You hereby waive any right to inspect or approve uses of the Published Information and waive any moral rights you may have in the Published Information. To the extent that you appear in the Published Information, you agree that we have the right to use (and to license to others to use) your name and likeness in connection with our use of the Published Information without any payment or other obligation to you. Without limitation, you hereby waive any rights to privacy, publicity and defamation, whether granted by statute or common law, that you may have in connection with the Published Information. You agree that we shall own all right, title and interest in and to the Published Information, any works derived therefrom, including any related copyrights. To the extent permissible by law, the Published Information shall be deemed a "work made for hire" for us pursuant to the Hong Kong Copyright Ordinance (Cap 528). No rights are granted to you hereunder other than as expressly set forth herein.</p>
        <h5>INTELLECTUAL PROPERTY RIGHTS</h5>
        <p>The Site and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by ..............., its licensors or other providers of such material and are protected by Hong Kong and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.</p>
        <p>This Agreement permits you to use the Site for your personal use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store or transmit any of the material on our Site, except as follows:</p>
        <ul>
            <li>Your computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials.</li>
            <li>You may store files that are automatically cached by your Web browser for display enhancement purposes.</li>
            <li>You may print or download one copy of a reasonable number of pages of the Website for your own personal, non-commercial use and not for further reproduction, publication or distribution.</li>
            <li>If we provide desktop, mobile or other applications for download, you may download a single copy to your computer or mobile device for each such computer or device solely for your own personal, non-commercial use, provided you agree to be bound by our end user license agreement for such applications.</li>
            <li>If we provide social media features with certain content, you may take such actions as are enabled by such features.</li>
        </ul>
        <p>You must not:</p>
        <ul>
            <li>Modify, copy, display, republish or create derivative works based on any materials from the Site.</li>
            <li>Use any illustrations, photographs, video or audio sequences or any graphics separately from the accompanying text.</li>
            <li>Delete or alter any copyright, trademark or other proprietary rights notices from copies of materials from the Site.</li>
            <li>Reverse engineer the Site or any of its underlying software.</li>
            <li>Access the Site in order to build a competitive product or service, or copy any ideas, features, functions or graphics available through the Site.</li>
        </ul>
        <p>This permission does not include any resale or commercial use of this Site or its contents; any collection and use of any content; any derivative use of this Site or its contents; any downloading or copying of account information for the benefit of a third party; programmatic access or any use of data mining, robots, or similar data gathering and extraction tools. This Site or any portion of this Site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of ................ You may not remove, decompile, disassemble or reverse engineer any Site software or use any network monitoring or discovery software to determine the Site architecture. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of ...............'s and our affiliates without express written consent. You may not access the Site in order to (a) build a competitive data-related commercial product or service, or (b) copy any features, functions or graphics of our Services. You may not use any meta tags or any other "hidden text" utilizing our name or trademarks without the express written consent of ................</p>
        <p>If you print, copy, modify, download or otherwise use or provide any other person with access to any part of the Site in breach of this Agreement, your right to use the Site will cease immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title or interest in or to the Site or any content on the Site is transferred to you, and all rights not expressly granted are reserved by ................ Any use of the Site not expressly permitted by this Agreement is a breach of this Agreement and may violate copyright, trademark and other laws.</p>
        <p>The ............... name, ............... logo and other identifying marks we use are our service marks or registered service marks or trademarks. Other products and company names mentioned on the Site may be trademarks of their respective owners. ...............'s service marks, trademarks and trade dress may not be used in any manner that is likely to cause confusion among customers or in any manner that disparages or discredits ............... or <a href="/">................com</a>. All other trademarks not owned by ............... or its subsidiaries that appear on the Site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by ............... or its subsidiaries.</p>
        <h5>PROHIBITED USES</h5>
        <p>Individual accounts are provided strictly for non-commercial use. The Site may only be accessed by a living human and not through any automated program, “bot” or other system designed for crawling the web. You may not use the Site for the purpose of gathering information for or transmitting unsolicited commercial phone calls, facsimile transmissions, email or email that makes use of headers, invalid or nonexistent domain names, or other means of deceptive addressing. You may not use the Site in a manner that violates any local, state, national and international laws including, but not limited to, any law or regulation concerning email, telephone solicitations or facsimile transmissions or the export of data or software to and from Hong Kong Special Administrative Region or other countries. You may not use this Site to intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the Hong Kong Securities and Futures Commission, any rules of any national or other securities exchange, including, without limitation, the Stock Exchange of Hong Kong Limited, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law. You may not use this Site to provide material support or resources (or to conceal or disguise the nature, location, source, or ownership of material support or resources) to any organization or organizations designated by the Hong Kong Special Administrative Region Government as a foreign terrorist organization pursuant to Cap. 575 United Nations (Anti-Terrorism Measures) Ordinance. You may not use this Site for the purpose of exploiting, harming or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information or otherwise. You may not export or re-export the Site or any portion thereof, or any software available on or through the Site, in violation of the export control laws or regulations of Hong Kong SAR. Any unauthorized use terminates the permission or license granted by ................ You are granted a limited, nonexclusive, nontransferable, revocable right to create a hyperlink to the home page of the Site so long as the link does not portray the Site, ..............., its affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive manner.</p>
        <p>Furthermore, you agree not to engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Site, or which, as determined by us, may harm ............... or users of the Site or expose them to liability.</p>
        <h5>LINKING TO THE WEBSITE AND SOCIAL MEDIA FEATURES</h5>
        <p>You may link to our homepage, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part without our express written consent.</p>
        <p>This Site may provide certain social media features that enable you to:</p>
        <ul>
            <li>Link from your own or certain third-party websites to certain content on this Site.</li>
            <li>Send e-mails or other communications with certain content, or links to certain content, on this Site.</li>
            <li>Cause limited portions of content on this Site to be displayed or appear to be displayed on your own or certain third-party websites.</li>
        </ul>
        <p>You may use these features solely as they are provided by us, solely with respect to the content they are displayed with and otherwise in accordance with any additional terms and conditions we provide with respect to such features. Subject to the foregoing, you must not:</p>
        <ul>
            <li>Establish a link from any website that is not owned by you.</li>
            <li>Cause the Site or portions of it to be displayed, or appear to be displayed by, for example, framing, deep linking or in-line linking, on any other site.</li>
            <li>Otherwise take any action with respect to the materials on this Website that is inconsistent with any other provision of these Terms of Use.</li>
        </ul>
        <p>The website from which you are linking, or on which you make certain content accessible, must comply in all respects with the Content Standards set out in these Terms of Use. You agree to cooperate with us in causing any unauthorized framing or linking immediately to cease. We reserve the right to withdraw linking permission without notice. We may disable all or any social media features and any links at any time without notice in our discretion.</p>
        <h5>LINKS FROM THE WEBSITE</h5>
        <p>If the Website contains links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to this Site, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.</p>
        <h5>REVIEWS, COMMENTS, COMMUNICATIONS AND OTHER CONTENT</h5>
        <p>Visitors may post reviews, comments, and other content; send messages and other communications; and submit suggestions, ideas, comments, questions, or other information ("Content"), so long as the Content is not illegal under any applicable state, federal or international laws and regulations, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, in violation of any contractual or fiduciary relationships, likely to deceive any person, promoting illegal or pornographic activity, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, malicious computer code, files or software, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." You may not use a false e-mail address, forge headers or manipulate identifiers, impersonate any person or entity, or otherwise mislead as to the origin of the Content. You agree not to act in a manner that negatively affects other users' ability to use our Site or Services, nor to harass or "stalk" another user. You agree not to interfere or disrupt our Services or servers or networks connected to our Services, or disobey any requirements, procedures, policies or regulations of networks connected to our Services, including using any device, software or routine to bypass our robot exclusion headers. ............... reserves the right (but not the obligation) to remove or edit such Content but does not regularly review posted content. We assume no liability for any action or inaction regarding transmissions, communications or Content provided by any user or third party. We have no liability or responsibility to anyone for performance or non-performance of monitoring the Content placed on the Site.</p>
        <p>You understand that all Content, whether publicly posted or privately transmitted, is the sole responsibility of the person from whom such Content originated. This means that you are solely responsible for all Content that you upload, post, email, transmit or otherwise make available while using our Services. We do not control the Content posted through our Services and, as such, do not guarantee the accuracy, integrity or quality of such Content. You understand that by using our Services, you may be exposed to Content that is offensive, indecent or objectionable. We are not liable for any Content under any circumstances, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available through our Services.</p>
        <p>If you do post Content or submit material, and unless we indicate otherwise, you grant ............... and its affiliates and service providers, and each of their and our respective licensees, successors, and assigns a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable license to use, reproduce, modify, adapt, publish, translate, perform, create derivative works from, distribute, and display such content throughout the world in any media and otherwise disclose to third parties any such Content for any purpose. You grant ............... and its affiliates and sublicensees the right to use the name that you submit in connection with such Content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the Content that you post; that you have the right to grant the license granted herein to us and our affiliates and service providers, and each of their and our respective licensees, successors, and assigns; that the Content is accurate; that use of the Content you supply does not violate this policy and will not cause injury to any person or entity; that the Content you post does not constitute a "trade secret" under applicable law and has not been misappropriated from a third party; that such Content does and will continue to comply with this Agreement, as amended; and that you will indemnify ............... or its affiliates for all claims resulting from Content you supply. We have the right but not the obligation to monitor and edit or remove any activity or Content. We take no responsibility and assume no liability for any Content posted by you or any third party. You understand and acknowledge that you are responsible for any Content you submit or contribute, and you, not ..............., have full responsibility for such content, including its legality, reliability, accuracy, and appropriateness.</p>
        <h5>UNLAWFUL ACTIVITY</h5>
        <p>We reserve the right to investigate complaints or reported violations of the Site Policies and to take any action we deem appropriate, including but not limited to reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to your profile, email addresses, usage history, posted materials, IP addresses and traffic information. YOU AGREE TO INDEMNIFY AND HOLD HARMLESS ............... AND ITS AFFILIATES, LICENSEES AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING OR AS A RESULT OF ITS INVESTIGATIONS AND FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</p>
        <h5>SECURITIES LAWS</h5>
        <p>Our website may include statements concerning our operations, prospects, strategies, financial condition, future economic performance and demand for our products or services, as well as our intentions, plans and objectives (particularly with respect to product and service offerings), and those of other companies and industries that are forward-looking statements. These statements are based upon a number of assumptions and estimates which are subject to significant uncertainties, many of which are beyond our control. When used on our Site, words like "anticipates," "expects," "believes," "estimates," "seeks," "plans," "intends," "will" and similar expressions are intended to identify forward-looking statements designed to fall within securities law safe harbors for forward-looking statements. Our website and the information contained on the Site does not constitute an offer or a solicitation of an offer for sale of any securities.</p>
        <h5>INFORMATION AND PRESS RELEASES</h5>
        <p>Our website contains information and press releases about us. We disclaim any duty or obligation to update this information or any such press releases. Information about companies other than ours contained in any press release or otherwise, should not be relied upon as being provided or endorsed by us.</p>
        <h5>DISCLAIMER OF WARRANTIES</h5>
        <p>The site and all content contained herein is provided by ............... on an "as is" and "as available" basis. ............... makes no representations or warranties of any kind, express or implied, as to the operation of this site or the information, content, materials, or products included on this site. You expressly agree that your use of this site is at your sole risk. Neither ............... nor any person associated with ............... makes any warranty or representation with respect to the completeness, security, reliability, quality, accuracy or availability of the site. Without limiting the foregoing, neither ............... nor anyone associated with ............... represents or warrants that the site, its content or any services or items obtained through the site will be accurate, reliable, error-free or uninterrupted, that defects will be corrected, that our site or the server that makes it available are free of viruses or other harmful components or that the site or any services or items obtained through the site will otherwise meet your needs or expectations.</p>
        <p>To the full extent permissible by applicable law, ............... disclaims all warranties, express or implied, statutorily or otherwise, including, but not limited to, implied warranties of merchantability, non-infringement, and fitness for a particular purpose. ............... does not warrant that this site, its servers, or e-mail sent from <a href="/">................com</a> are free of viruses or other harmful components. To the fullest extent permitted by law, ............... will not be liable for any damages of any kind arising from the use of this site, including, but not limited to indirect, special, incidental or consequential damages (including damages for loss of business, loss of profits, litigation, or the like), whether based on breach of contract, breach of warranty, tort (including negligence), product liability or otherwise, even if advised of the possibility of such damages. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection. The negation and limitation of damages set forth above are fundamental elements of the basis of the bargain between us and you. This site and the products, services, and information presented would not be provided without such limitations.</p>
        <p>We and our affiliates shall not be liable for any loss, injury, claim, liability, or damage of any kind resulting in any way from (a) any errors in or omissions from the site or any services or products obtainable from the site, (b) the unavailability or interruption of the site or any features of the site, (c) your use of the site or with the delay or inability to use the site, (d) the content contained on the site, or (e) any delay or failure in performance beyond our control.</p>
        <h5>LIMITATION OF LIABILITY</h5>
        <p>To the fullest extent permitted by law, the aggregate liability of ..............., its subsidiaries and its affiliates in connection with any claim arising out of or relating to the site, or the products, services or information provided by the site shall not exceed HK$ 100 and that amount shall be in lieu of all other remedies which you may have against us and our affiliates.</p>
        <p>Any cause of action you may have with respect to the site or any products or services purchased using the site must be brought by you within one year after the cause of action arises or be forever waived and barred.</p>
        <h5>INDEMNIFICATION</h5>
        <p>You agree to indemnify, defend and hold us and our partners, agents, officers, directors, employees, subcontractors, successors and assigns, third party suppliers of information and documents, attorneys, advertisers, product and service providers and affiliates harmless from any liability, loss, claim and expense, including reasonable attorney's fees, related to your violation of this Agreement, the Site Policies or use of the Site.</p>
        <h5>APPLICABLE LAW</h5>
        <p>You agree that the laws of the Hong Kong Special Administrative Region, without regard to principles of conflict of laws, will govern this Agreement and the Site Policies and any dispute of any sort that might arise between you and ............... or its affiliates.</p>
        <h5>DISPUTES</h5>
        <p>Any dispute, difference, claim, or unresolved controversy arising out of or relating to the Site Policies, your visit to ................com or to products you purchase through the Site, including the existence, validity, interpretation, performance, breach or termination thereof shall be referred to the Hong Kong International Arbitration Centre under the Hong Kong International Arbitration Center Administered Arbitration rules in force when the Notice of Arbitration is submitted, except that, to the extent you have in any manner violated or threatened to violate ...............'s intellectual property rights, ............... may seek injunctive or other appropriate relief in any court in Hong Kong Special Administrative Region, and you consent to exclusive jurisdiction and venue in such courts. The seat of arbitration shall be Hong Kong. The number of arbitrators shall be one. The arbitration proceedings shall be conducted in English. The arbitrator's award shall be binding and may be entered as a judgment in any court of competent jurisdiction. Each party will bear its own costs with respect to any disputes arising under this Agreement and the Site Policies. To the fullest extent permitted by applicable law, no arbitration under this Agreement and the Site Policies shall be joined to an arbitration involving any other party subject to this Agreement and the Site Policies, whether through class arbitration proceedings or otherwise. By using the Site, you specifically agree to be bound by this arbitration provision, and agree that all disputes must be arbitrated on an individual basis. You specifically agree that you have no right or authority to bring any dispute as a class, collective or representative action.</p>
        <h5>MISCELLANEOUS</h5>
        <p>The language in this Agreement shall be interpreted as to its fair meaning and not strictly for or against any party. The Terms of Use Agreement, including any Content or Published Information provided by you on the Site may be automatically assigned by us in our sole discretion to a third party in the event of an acquisition, sale, merger, or other change of control of ................ Should any part of the Terms of Use Agreement be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect. To the extent that anything in or associated with the Site is in conflict or inconsistent with this Agreement, the Terms of Use Agreement shall take precedence. Our failure to enforce any provision of the Terms of Use Agreement shall not be deemed a waiver of such provision nor of the right to enforce such provision. Our rights under the Terms of Use Agreement shall survive any termination of the Terms of Use Agreement.</p>
        <h5>OTHER SITE POLICIES AND MODIFICATION</h5>
        <p>From time to time, we may post revised versions of existing policies or new policies on our website. Please review all of our other policies posted on this Site. These policies also govern your visit to <a href="/">................com</a>. We reserve the right to make changes to our Site, policies, and this Terms of Use Agreement at any time.</p>
        <h5>GEOGRAPHIC RESTRICTIONS</h5>
        <p>Access to the Site may not be legal by certain persons or in certain countries. If you access the Site from outside Hong Kong and receive its Services, you do so on your own initiative and are responsible for compliance with local laws.</p>
        <h5>NOTICE AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT INFRINGEMENT</h5>
        <p>If you believe that your work has been copied in a way that constitutes copyright infringement, please provide ...............'s copyright agent the written information specified below. Please note that this procedure is exclusively for notifying ............... and its affiliates that your copyrighted material has been infringed.</p>
        <p>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</p>
        <ul>
            <li>A description of the copyrighted work that you claim has been infringed upon;</li>
            <li>A description of where the material that you claim is infringing is located on the Site;</li>
            <li>Your address, telephone number, and e-mail address;</li>
            <li>A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
            <li>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</li>
        </ul>
        <p>...............'s Copyright Agent for notice of claims of copyright infringement on its website can be reached at <a href="mailto:copyright@................com">copyright@................com</a>
        </p>
        <p>Effective Date: August 10, 2020</p>
    </div>
@endsection
